baseURL = "https://justinoeuf.github.io/hugo_blog_public/"
languageCode = "en-us"
title = "Blog Page Template"
theme = "hugo-coder"

paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

publishDir = "docs"
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Your Name, eg Benjamin Banneker"
description = "Personal Blog"
keywords = "blog,developer,personal"
info = ["Some info, eg African American Historical Figure"]
avatarURL = "images/profile_pic.jpg"
footerContent = "A note on the images in this Demo-- they can be centered wiht a bit of html coding. I did not do that here." 
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2021

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 4
url = "https://github.com/"

[[params.social]]
name = "Facebook"
icon = "fa fa-facebook"
weight = 1
url = "https://www.facebook.com/zuck"

[[params.social]]
name = "Instagram"
icon = "fa fa-instagram"
weight = 2
url = "https://www.instagram.com/natgeo"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/barackobama/"

# Menu bar features

[[languages.en.menu.main]]
name = "Posts"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "about/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

#[[languages.en.menu.main]]
#name = "Contact me"
#weight = 5
#url = "contact/"

#[[languages.en.menu.main]]
#name = "Publications"
#weight = 5
#url = "publications/"
